/*jslint browser: true*/
/*globals canvasDatagrid: false*/
var data;
document.addEventListener('DOMContentLoaded', function () {
    'use strict';
    var grid = canvasDatagrid({
        parentNode: document.body,
        data: data,
        schema: [
            {
                name: 'entity',
                title: 'Entity',
                format: function (cell) {
                    return cell.value;
                }
            },
            {
                name: 'currency',
                title: 'Currency'
            },
            {
                name: 'alphabeticCode',
                title: 'Alphabetic Code'
            },
            {
                name: 'numericCode',
                title: 'Numeric Code'
            },
            {
                name: 'minorUnit',
                title: 'Minor Unit'
            },
        ],
        tree: true
    });
    grid.addEventListener('expandtree', function (e) {
        e.treeGrid.data = data;
    });
    return;
});
data = [
    {"entity": "AFGHANISTAN", "currency": "Afghani", "alphabeticCode": "AFN", "numericCode": "971", "minorUnit": "2", "fund": ""},
    {"entity": "ÅLAND ISLANDS", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "ALBANIA", "currency": "Lek", "alphabeticCode": "ALL", "numericCode": "008", "minorUnit": "2", "fund": ""},
    {"entity": "ALGERIA", "currency": "Algerian Dinar", "alphabeticCode": "DZD", "numericCode": "012", "minorUnit": "2", "fund": ""},
    {"entity": "AMERICAN SAMOA", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "ANDORRA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "ANGOLA", "currency": "Kwanza", "alphabeticCode": "AOA", "numericCode": "973", "minorUnit": "2", "fund": ""},
    {"entity": "ANGUILLA", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "ANTARCTICA", "currency": "No universal currency", "alphabeticCode": "", "numericCode": "", "minorUnit": "", "fund": ""},
    {"entity": "ANTIGUA AND BARBUDA", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "ARGENTINA", "currency": "Argentine Peso", "alphabeticCode": "ARS", "numericCode": "032", "minorUnit": "2", "fund": ""},
    {"entity": "ARMENIA", "currency": "Armenian Dram", "alphabeticCode": "AMD", "numericCode": "051", "minorUnit": "2", "fund": ""},
    {"entity": "ARUBA", "currency": "Aruban Florin", "alphabeticCode": "AWG", "numericCode": "533", "minorUnit": "2", "fund": ""},
    {"entity": "AUSTRALIA", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "AUSTRIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "AZERBAIJAN", "currency": "Azerbaijan Manat", "alphabeticCode": "AZN", "numericCode": "944", "minorUnit": "2", "fund": ""},
    {"entity": "BAHAMAS (THE)", "currency": "Bahamian Dollar", "alphabeticCode": "BSD", "numericCode": "044", "minorUnit": "2", "fund": ""},
    {"entity": "BAHRAIN", "currency": "Bahraini Dinar", "alphabeticCode": "BHD", "numericCode": "048", "minorUnit": "3", "fund": ""},
    {"entity": "BANGLADESH", "currency": "Taka", "alphabeticCode": "BDT", "numericCode": "050", "minorUnit": "2", "fund": ""},
    {"entity": "BARBADOS", "currency": "Barbados Dollar", "alphabeticCode": "BBD", "numericCode": "052", "minorUnit": "2", "fund": ""},
    {"entity": "BELARUS", "currency": "Belarusian Ruble", "alphabeticCode": "BYN", "numericCode": "933", "minorUnit": "2", "fund": ""},
    {"entity": "BELGIUM", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "BELIZE", "currency": "Belize Dollar", "alphabeticCode": "BZD", "numericCode": "084", "minorUnit": "2", "fund": ""},
    {"entity": "BENIN", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "BERMUDA", "currency": "Bermudian Dollar", "alphabeticCode": "BMD", "numericCode": "060", "minorUnit": "2", "fund": ""},
    {"entity": "BHUTAN", "currency": "Indian Rupee", "alphabeticCode": "INR", "numericCode": "356", "minorUnit": "2", "fund": ""},
    {"entity": "BHUTAN", "currency": "Ngultrum", "alphabeticCode": "BTN", "numericCode": "064", "minorUnit": "2", "fund": ""},
    {"entity": "BOLIVIA (PLURINATIONAL STATE OF)", "currency": "Boliviano", "alphabeticCode": "BOB", "numericCode": "068", "minorUnit": "2", "fund": ""},
    {"entity": "BOLIVIA (PLURINATIONAL STATE OF)", "currency": "Mvdol", "alphabeticCode": "BOV", "numericCode": "984", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "BONAIRE SINT EUSTATIUS AND SABA", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "BOSNIA AND HERZEGOVINA", "currency": "Convertible Mark", "alphabeticCode": "BAM", "numericCode": "977", "minorUnit": "2", "fund": ""},
    {"entity": "BOTSWANA", "currency": "Pula", "alphabeticCode": "BWP", "numericCode": "072", "minorUnit": "2", "fund": ""},
    {"entity": "BOUVET ISLAND", "currency": "Norwegian Krone", "alphabeticCode": "NOK", "numericCode": "578", "minorUnit": "2", "fund": ""},
    {"entity": "BRAZIL", "currency": "Brazilian Real", "alphabeticCode": "BRL", "numericCode": "986", "minorUnit": "2", "fund": ""},
    {"entity": "BRITISH INDIAN OCEAN TERRITORY (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "BRUNEI DARUSSALAM", "currency": "Brunei Dollar", "alphabeticCode": "BND", "numericCode": "096", "minorUnit": "2", "fund": ""},
    {"entity": "BULGARIA", "currency": "Bulgarian Lev", "alphabeticCode": "BGN", "numericCode": "975", "minorUnit": "2", "fund": ""},
    {"entity": "BURKINA FASO", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "BURUNDI", "currency": "Burundi Franc", "alphabeticCode": "BIF", "numericCode": "108", "minorUnit": "0", "fund": ""},
    {"entity": "CABO VERDE", "currency": "Cabo Verde Escudo", "alphabeticCode": "CVE", "numericCode": "132", "minorUnit": "2", "fund": ""},
    {"entity": "CAMBODIA", "currency": "Riel", "alphabeticCode": "KHR", "numericCode": "116", "minorUnit": "2", "fund": ""},
    {"entity": "CAMEROON", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "CANADA", "currency": "Canadian Dollar", "alphabeticCode": "CAD", "numericCode": "124", "minorUnit": "2", "fund": ""},
    {"entity": "CAYMAN ISLANDS (THE)", "currency": "Cayman Islands Dollar", "alphabeticCode": "KYD", "numericCode": "136", "minorUnit": "2", "fund": ""},
    {"entity": "CENTRAL AFRICAN REPUBLIC (THE)", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "CHAD", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "CHILE", "currency": "Chilean Peso", "alphabeticCode": "CLP", "numericCode": "152", "minorUnit": "0", "fund": ""},
    {"entity": "CHILE", "currency": "Unidad de Fomento", "alphabeticCode": "CLF", "numericCode": "990", "minorUnit": "4", "fund": "TRUE"},
    {"entity": "CHINA", "currency": "Yuan Renminbi", "alphabeticCode": "CNY", "numericCode": "156", "minorUnit": "2", "fund": ""},
    {"entity": "CHRISTMAS ISLAND", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "COCOS (KEELING) ISLANDS (THE)", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "COLOMBIA", "currency": "Colombian Peso", "alphabeticCode": "COP", "numericCode": "170", "minorUnit": "2", "fund": ""},
    {"entity": "COLOMBIA", "currency": "Unidad de Valor Real", "alphabeticCode": "COU", "numericCode": "970", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "COMOROS (THE)", "currency": "Comorian Franc ", "alphabeticCode": "KMF", "numericCode": "174", "minorUnit": "0", "fund": ""},
    {"entity": "CONGO (THE DEMOCRATIC REPUBLIC OF THE)", "currency": "Congolese Franc", "alphabeticCode": "CDF", "numericCode": "976", "minorUnit": "2", "fund": ""},
    {"entity": "CONGO (THE)", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "COOK ISLANDS (THE)", "currency": "New Zealand Dollar", "alphabeticCode": "NZD", "numericCode": "554", "minorUnit": "2", "fund": ""},
    {"entity": "COSTA RICA", "currency": "Costa Rican Colon", "alphabeticCode": "CRC", "numericCode": "188", "minorUnit": "2", "fund": ""},
    {"entity": "CÔTE D'IVOIRE", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "CROATIA", "currency": "Kuna", "alphabeticCode": "HRK", "numericCode": "191", "minorUnit": "2", "fund": ""},
    {"entity": "CUBA", "currency": "Cuban Peso", "alphabeticCode": "CUP", "numericCode": "192", "minorUnit": "2", "fund": ""},
    {"entity": "CUBA", "currency": "Peso Convertible", "alphabeticCode": "CUC", "numericCode": "931", "minorUnit": "2", "fund": ""},
    {"entity": "CURAÇAO", "currency": "Netherlands Antillean Guilder", "alphabeticCode": "ANG", "numericCode": "532", "minorUnit": "2", "fund": ""},
    {"entity": "CYPRUS", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "CZECHIA", "currency": "Czech Koruna", "alphabeticCode": "CZK", "numericCode": "203", "minorUnit": "2", "fund": ""},
    {"entity": "DENMARK", "currency": "Danish Krone", "alphabeticCode": "DKK", "numericCode": "208", "minorUnit": "2", "fund": ""},
    {"entity": "DJIBOUTI", "currency": "Djibouti Franc", "alphabeticCode": "DJF", "numericCode": "262", "minorUnit": "0", "fund": ""},
    {"entity": "DOMINICA", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "DOMINICAN REPUBLIC (THE)", "currency": "Dominican Peso", "alphabeticCode": "DOP", "numericCode": "214", "minorUnit": "2", "fund": ""},
    {"entity": "ECUADOR", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "EGYPT", "currency": "Egyptian Pound", "alphabeticCode": "EGP", "numericCode": "818", "minorUnit": "2", "fund": ""},
    {"entity": "EL SALVADOR", "currency": "El Salvador Colon", "alphabeticCode": "SVC", "numericCode": "222", "minorUnit": "2", "fund": ""},
    {"entity": "EL SALVADOR", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "EQUATORIAL GUINEA", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "ERITREA", "currency": "Nakfa", "alphabeticCode": "ERN", "numericCode": "232", "minorUnit": "2", "fund": ""},
    {"entity": "ESTONIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "ETHIOPIA", "currency": "Ethiopian Birr", "alphabeticCode": "ETB", "numericCode": "230", "minorUnit": "2", "fund": ""},
    {"entity": "EUROPEAN UNION", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "FALKLAND ISLANDS (THE) [MALVINAS]", "currency": "Falkland Islands Pound", "alphabeticCode": "FKP", "numericCode": "238", "minorUnit": "2", "fund": ""},
    {"entity": "FAROE ISLANDS (THE)", "currency": "Danish Krone", "alphabeticCode": "DKK", "numericCode": "208", "minorUnit": "2", "fund": ""},
    {"entity": "FIJI", "currency": "Fiji Dollar", "alphabeticCode": "FJD", "numericCode": "242", "minorUnit": "2", "fund": ""},
    {"entity": "FINLAND", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "FRANCE", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "FRENCH GUIANA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "FRENCH POLYNESIA", "currency": "CFP Franc", "alphabeticCode": "XPF", "numericCode": "953", "minorUnit": "0", "fund": ""},
    {"entity": "FRENCH SOUTHERN TERRITORIES (THE)", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "GABON", "currency": "CFA Franc BEAC", "alphabeticCode": "XAF", "numericCode": "950", "minorUnit": "0", "fund": ""},
    {"entity": "GAMBIA (THE)", "currency": "Dalasi", "alphabeticCode": "GMD", "numericCode": "270", "minorUnit": "2", "fund": ""},
    {"entity": "GEORGIA", "currency": "Lari", "alphabeticCode": "GEL", "numericCode": "981", "minorUnit": "2", "fund": ""},
    {"entity": "GERMANY", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "GHANA", "currency": "Ghana Cedi", "alphabeticCode": "GHS", "numericCode": "936", "minorUnit": "2", "fund": ""},
    {"entity": "GIBRALTAR", "currency": "Gibraltar Pound", "alphabeticCode": "GIP", "numericCode": "292", "minorUnit": "2", "fund": ""},
    {"entity": "GREECE", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "GREENLAND", "currency": "Danish Krone", "alphabeticCode": "DKK", "numericCode": "208", "minorUnit": "2", "fund": ""},
    {"entity": "GRENADA", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "GUADELOUPE", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "GUAM", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "GUATEMALA", "currency": "Quetzal", "alphabeticCode": "GTQ", "numericCode": "320", "minorUnit": "2", "fund": ""},
    {"entity": "GUERNSEY", "currency": "Pound Sterling", "alphabeticCode": "GBP", "numericCode": "826", "minorUnit": "2", "fund": ""},
    {"entity": "GUINEA", "currency": "Guinean Franc", "alphabeticCode": "GNF", "numericCode": "324", "minorUnit": "0", "fund": ""},
    {"entity": "GUINEA-BISSAU", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "GUYANA", "currency": "Guyana Dollar", "alphabeticCode": "GYD", "numericCode": "328", "minorUnit": "2", "fund": ""},
    {"entity": "HAITI", "currency": "Gourde", "alphabeticCode": "HTG", "numericCode": "332", "minorUnit": "2", "fund": ""},
    {"entity": "HAITI", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "HEARD ISLAND AND McDONALD ISLANDS", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "HOLY SEE (THE)", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "HONDURAS", "currency": "Lempira", "alphabeticCode": "HNL", "numericCode": "340", "minorUnit": "2", "fund": ""},
    {"entity": "HONG KONG", "currency": "Hong Kong Dollar", "alphabeticCode": "HKD", "numericCode": "344", "minorUnit": "2", "fund": ""},
    {"entity": "HUNGARY", "currency": "Forint", "alphabeticCode": "HUF", "numericCode": "348", "minorUnit": "2", "fund": ""},
    {"entity": "ICELAND", "currency": "Iceland Krona", "alphabeticCode": "ISK", "numericCode": "352", "minorUnit": "0", "fund": ""},
    {"entity": "INDIA", "currency": "Indian Rupee", "alphabeticCode": "INR", "numericCode": "356", "minorUnit": "2", "fund": ""},
    {"entity": "INDONESIA", "currency": "Rupiah", "alphabeticCode": "IDR", "numericCode": "360", "minorUnit": "2", "fund": ""},
    {"entity": "INTERNATIONAL MONETARY FUND (IMF) ", "currency": "SDR (Special Drawing Right)", "alphabeticCode": "XDR", "numericCode": "960", "minorUnit": "N.A.", "fund": ""},
    {"entity": "IRAN (ISLAMIC REPUBLIC OF)", "currency": "Iranian Rial", "alphabeticCode": "IRR", "numericCode": "364", "minorUnit": "2", "fund": ""},
    {"entity": "IRAQ", "currency": "Iraqi Dinar", "alphabeticCode": "IQD", "numericCode": "368", "minorUnit": "3", "fund": ""},
    {"entity": "IRELAND", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "ISLE OF MAN", "currency": "Pound Sterling", "alphabeticCode": "GBP", "numericCode": "826", "minorUnit": "2", "fund": ""},
    {"entity": "ISRAEL", "currency": "New Israeli Sheqel", "alphabeticCode": "ILS", "numericCode": "376", "minorUnit": "2", "fund": ""},
    {"entity": "ITALY", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "JAMAICA", "currency": "Jamaican Dollar", "alphabeticCode": "JMD", "numericCode": "388", "minorUnit": "2", "fund": ""},
    {"entity": "JAPAN", "currency": "Yen", "alphabeticCode": "JPY", "numericCode": "392", "minorUnit": "0", "fund": ""},
    {"entity": "JERSEY", "currency": "Pound Sterling", "alphabeticCode": "GBP", "numericCode": "826", "minorUnit": "2", "fund": ""},
    {"entity": "JORDAN", "currency": "Jordanian Dinar", "alphabeticCode": "JOD", "numericCode": "400", "minorUnit": "3", "fund": ""},
    {"entity": "KAZAKHSTAN", "currency": "Tenge", "alphabeticCode": "KZT", "numericCode": "398", "minorUnit": "2", "fund": ""},
    {"entity": "KENYA", "currency": "Kenyan Shilling", "alphabeticCode": "KES", "numericCode": "404", "minorUnit": "2", "fund": ""},
    {"entity": "KIRIBATI", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)", "currency": "North Korean Won", "alphabeticCode": "KPW", "numericCode": "408", "minorUnit": "2", "fund": ""},
    {"entity": "KOREA (THE REPUBLIC OF)", "currency": "Won", "alphabeticCode": "KRW", "numericCode": "410", "minorUnit": "0", "fund": ""},
    {"entity": "KUWAIT", "currency": "Kuwaiti Dinar", "alphabeticCode": "KWD", "numericCode": "414", "minorUnit": "3", "fund": ""},
    {"entity": "KYRGYZSTAN", "currency": "Som", "alphabeticCode": "KGS", "numericCode": "417", "minorUnit": "2", "fund": ""},
    {"entity": "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)", "currency": "Lao Kip", "alphabeticCode": "LAK", "numericCode": "418", "minorUnit": "2", "fund": ""},
    {"entity": "LATVIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "LEBANON", "currency": "Lebanese Pound", "alphabeticCode": "LBP", "numericCode": "422", "minorUnit": "2", "fund": ""},
    {"entity": "LESOTHO", "currency": "Loti", "alphabeticCode": "LSL", "numericCode": "426", "minorUnit": "2", "fund": ""},
    {"entity": "LESOTHO", "currency": "Rand", "alphabeticCode": "ZAR", "numericCode": "710", "minorUnit": "2", "fund": ""},
    {"entity": "LIBERIA", "currency": "Liberian Dollar", "alphabeticCode": "LRD", "numericCode": "430", "minorUnit": "2", "fund": ""},
    {"entity": "LIBYA", "currency": "Libyan Dinar", "alphabeticCode": "LYD", "numericCode": "434", "minorUnit": "3", "fund": ""},
    {"entity": "LIECHTENSTEIN", "currency": "Swiss Franc", "alphabeticCode": "CHF", "numericCode": "756", "minorUnit": "2", "fund": ""},
    {"entity": "LITHUANIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "LUXEMBOURG", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MACAO", "currency": "Pataca", "alphabeticCode": "MOP", "numericCode": "446", "minorUnit": "2", "fund": ""},
    {"entity": "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)", "currency": "Denar", "alphabeticCode": "MKD", "numericCode": "807", "minorUnit": "2", "fund": ""},
    {"entity": "MADAGASCAR", "currency": "Malagasy Ariary", "alphabeticCode": "MGA", "numericCode": "969", "minorUnit": "2", "fund": ""},
    {"entity": "MALAWI", "currency": "Malawi Kwacha", "alphabeticCode": "MWK", "numericCode": "454", "minorUnit": "2", "fund": ""},
    {"entity": "MALAYSIA", "currency": "Malaysian Ringgit", "alphabeticCode": "MYR", "numericCode": "458", "minorUnit": "2", "fund": ""},
    {"entity": "MALDIVES", "currency": "Rufiyaa", "alphabeticCode": "MVR", "numericCode": "462", "minorUnit": "2", "fund": ""},
    {"entity": "MALI", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "MALTA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MARSHALL ISLANDS (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "MARTINIQUE", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MAURITANIA", "currency": "Ouguiya", "alphabeticCode": "MRO", "numericCode": "478", "minorUnit": "2", "fund": ""},
    {"entity": "MAURITIUS", "currency": "Mauritius Rupee", "alphabeticCode": "MUR", "numericCode": "480", "minorUnit": "2", "fund": ""},
    {"entity": "MAYOTTE", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP", "currency": "ADB Unit of Account", "alphabeticCode": "XUA", "numericCode": "965", "minorUnit": "N.A.", "fund": ""},
    {"entity": "MEXICO", "currency": "Mexican Peso", "alphabeticCode": "MXN", "numericCode": "484", "minorUnit": "2", "fund": ""},
    {"entity": "MEXICO", "currency": "Mexican Unidad de Inversion (UDI)", "alphabeticCode": "MXV", "numericCode": "979", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "MICRONESIA (FEDERATED STATES OF)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "MOLDOVA (THE REPUBLIC OF)", "currency": "Moldovan Leu", "alphabeticCode": "MDL", "numericCode": "498", "minorUnit": "2", "fund": ""},
    {"entity": "MONACO", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MONGOLIA", "currency": "Tugrik", "alphabeticCode": "MNT", "numericCode": "496", "minorUnit": "2", "fund": ""},
    {"entity": "MONTENEGRO", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "MONTSERRAT", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "MOROCCO", "currency": "Moroccan Dirham", "alphabeticCode": "MAD", "numericCode": "504", "minorUnit": "2", "fund": ""},
    {"entity": "MOZAMBIQUE", "currency": "Mozambique Metical", "alphabeticCode": "MZN", "numericCode": "943", "minorUnit": "2", "fund": ""},
    {"entity": "MYANMAR", "currency": "Kyat", "alphabeticCode": "MMK", "numericCode": "104", "minorUnit": "2", "fund": ""},
    {"entity": "NAMIBIA", "currency": "Namibia Dollar", "alphabeticCode": "NAD", "numericCode": "516", "minorUnit": "2", "fund": ""},
    {"entity": "NAMIBIA", "currency": "Rand", "alphabeticCode": "ZAR", "numericCode": "710", "minorUnit": "2", "fund": ""},
    {"entity": "NAURU", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "NEPAL", "currency": "Nepalese Rupee", "alphabeticCode": "NPR", "numericCode": "524", "minorUnit": "2", "fund": ""},
    {"entity": "NETHERLANDS (THE)", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "NEW CALEDONIA", "currency": "CFP Franc", "alphabeticCode": "XPF", "numericCode": "953", "minorUnit": "0", "fund": ""},
    {"entity": "NEW ZEALAND", "currency": "New Zealand Dollar", "alphabeticCode": "NZD", "numericCode": "554", "minorUnit": "2", "fund": ""},
    {"entity": "NICARAGUA", "currency": "Cordoba Oro", "alphabeticCode": "NIO", "numericCode": "558", "minorUnit": "2", "fund": ""},
    {"entity": "NIGER (THE)", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "NIGERIA", "currency": "Naira", "alphabeticCode": "NGN", "numericCode": "566", "minorUnit": "2", "fund": ""},
    {"entity": "NIUE", "currency": "New Zealand Dollar", "alphabeticCode": "NZD", "numericCode": "554", "minorUnit": "2", "fund": ""},
    {"entity": "NORFOLK ISLAND", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "NORTHERN MARIANA ISLANDS (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "NORWAY", "currency": "Norwegian Krone", "alphabeticCode": "NOK", "numericCode": "578", "minorUnit": "2", "fund": ""},
    {"entity": "OMAN", "currency": "Rial Omani", "alphabeticCode": "OMR", "numericCode": "512", "minorUnit": "3", "fund": ""},
    {"entity": "PAKISTAN", "currency": "Pakistan Rupee", "alphabeticCode": "PKR", "numericCode": "586", "minorUnit": "2", "fund": ""},
    {"entity": "PALAU", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "PALESTINE STATE OF", "currency": "No universal currency", "alphabeticCode": "", "numericCode": "", "minorUnit": "", "fund": ""},
    {"entity": "PANAMA", "currency": "Balboa", "alphabeticCode": "PAB", "numericCode": "590", "minorUnit": "2", "fund": ""},
    {"entity": "PANAMA", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "PAPUA NEW GUINEA", "currency": "Kina", "alphabeticCode": "PGK", "numericCode": "598", "minorUnit": "2", "fund": ""},
    {"entity": "PARAGUAY", "currency": "Guarani", "alphabeticCode": "PYG", "numericCode": "600", "minorUnit": "0", "fund": ""},
    {"entity": "PERU", "currency": "Sol", "alphabeticCode": "PEN", "numericCode": "604", "minorUnit": "2", "fund": ""},
    {"entity": "PHILIPPINES (THE)", "currency": "Philippine Peso", "alphabeticCode": "PHP", "numericCode": "608", "minorUnit": "2", "fund": ""},
    {"entity": "PITCAIRN", "currency": "New Zealand Dollar", "alphabeticCode": "NZD", "numericCode": "554", "minorUnit": "2", "fund": ""},
    {"entity": "POLAND", "currency": "Zloty", "alphabeticCode": "PLN", "numericCode": "985", "minorUnit": "2", "fund": ""},
    {"entity": "PORTUGAL", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "PUERTO RICO", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "QATAR", "currency": "Qatari Rial", "alphabeticCode": "QAR", "numericCode": "634", "minorUnit": "2", "fund": ""},
    {"entity": "RÉUNION", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "ROMANIA", "currency": "Romanian Leu", "alphabeticCode": "RON", "numericCode": "946", "minorUnit": "2", "fund": ""},
    {"entity": "RUSSIAN FEDERATION (THE)", "currency": "Russian Ruble", "alphabeticCode": "RUB", "numericCode": "643", "minorUnit": "2", "fund": ""},
    {"entity": "RWANDA", "currency": "Rwanda Franc", "alphabeticCode": "RWF", "numericCode": "646", "minorUnit": "0", "fund": ""},
    {"entity": "SAINT BARTHÉLEMY", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SAINT KITTS AND NEVIS", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "SAINT LUCIA", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "SAINT MARTIN (FRENCH PART)", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SAINT PIERRE AND MIQUELON", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SAINT VINCENT AND THE GRENADINES", "currency": "East Caribbean Dollar", "alphabeticCode": "XCD", "numericCode": "951", "minorUnit": "2", "fund": ""},
    {"entity": "SAMOA", "currency": "Tala", "alphabeticCode": "WST", "numericCode": "882", "minorUnit": "2", "fund": ""},
    {"entity": "SAN MARINO", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SAO TOME AND PRINCIPE", "currency": "Dobra", "alphabeticCode": "STD", "numericCode": "678", "minorUnit": "2", "fund": ""},
    {"entity": "SAUDI ARABIA", "currency": "Saudi Riyal", "alphabeticCode": "SAR", "numericCode": "682", "minorUnit": "2", "fund": ""},
    {"entity": "SENEGAL", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "SERBIA", "currency": "Serbian Dinar", "alphabeticCode": "RSD", "numericCode": "941", "minorUnit": "2", "fund": ""},
    {"entity": "SEYCHELLES", "currency": "Seychelles Rupee", "alphabeticCode": "SCR", "numericCode": "690", "minorUnit": "2", "fund": ""},
    {"entity": "SIERRA LEONE", "currency": "Leone", "alphabeticCode": "SLL", "numericCode": "694", "minorUnit": "2", "fund": ""},
    {"entity": "SINGAPORE", "currency": "Singapore Dollar", "alphabeticCode": "SGD", "numericCode": "702", "minorUnit": "2", "fund": ""},
    {"entity": "SINT MAARTEN (DUTCH PART)", "currency": "Netherlands Antillean Guilder", "alphabeticCode": "ANG", "numericCode": "532", "minorUnit": "2", "fund": ""},
    {"entity": "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE", "currency": "Sucre", "alphabeticCode": "XSU", "numericCode": "994", "minorUnit": "N.A.", "fund": ""},
    {"entity": "SLOVAKIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SLOVENIA", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SOLOMON ISLANDS", "currency": "Solomon Islands Dollar", "alphabeticCode": "SBD", "numericCode": "090", "minorUnit": "2", "fund": ""},
    {"entity": "SOMALIA", "currency": "Somali Shilling", "alphabeticCode": "SOS", "numericCode": "706", "minorUnit": "2", "fund": ""},
    {"entity": "SOUTH AFRICA", "currency": "Rand", "alphabeticCode": "ZAR", "numericCode": "710", "minorUnit": "2", "fund": ""},
    {"entity": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "currency": "No universal currency", "alphabeticCode": "", "numericCode": "", "minorUnit": "", "fund": ""},
    {"entity": "SOUTH SUDAN", "currency": "South Sudanese Pound", "alphabeticCode": "SSP", "numericCode": "728", "minorUnit": "2", "fund": ""},
    {"entity": "SPAIN", "currency": "Euro", "alphabeticCode": "EUR", "numericCode": "978", "minorUnit": "2", "fund": ""},
    {"entity": "SRI LANKA", "currency": "Sri Lanka Rupee", "alphabeticCode": "LKR", "numericCode": "144", "minorUnit": "2", "fund": ""},
    {"entity": "SUDAN (THE)", "currency": "Sudanese Pound", "alphabeticCode": "SDG", "numericCode": "938", "minorUnit": "2", "fund": ""},
    {"entity": "SURINAME", "currency": "Surinam Dollar", "alphabeticCode": "SRD", "numericCode": "968", "minorUnit": "2", "fund": ""},
    {"entity": "SVALBARD AND JAN MAYEN", "currency": "Norwegian Krone", "alphabeticCode": "NOK", "numericCode": "578", "minorUnit": "2", "fund": ""},
    {"entity": "SWAZILAND", "currency": "Lilangeni", "alphabeticCode": "SZL", "numericCode": "748", "minorUnit": "2", "fund": ""},
    {"entity": "SWEDEN", "currency": "Swedish Krona", "alphabeticCode": "SEK", "numericCode": "752", "minorUnit": "2", "fund": ""},
    {"entity": "SWITZERLAND", "currency": "Swiss Franc", "alphabeticCode": "CHF", "numericCode": "756", "minorUnit": "2", "fund": ""},
    {"entity": "SWITZERLAND", "currency": "WIR Euro", "alphabeticCode": "CHE", "numericCode": "947", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "SWITZERLAND", "currency": "WIR Franc", "alphabeticCode": "CHW", "numericCode": "948", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "SYRIAN ARAB REPUBLIC", "currency": "Syrian Pound", "alphabeticCode": "SYP", "numericCode": "760", "minorUnit": "2", "fund": ""},
    {"entity": "TAIWAN (PROVINCE OF CHINA)", "currency": "New Taiwan Dollar", "alphabeticCode": "TWD", "numericCode": "901", "minorUnit": "2", "fund": ""},
    {"entity": "TAJIKISTAN", "currency": "Somoni", "alphabeticCode": "TJS", "numericCode": "972", "minorUnit": "2", "fund": ""},
    {"entity": "TANZANIA UNITED REPUBLIC OF", "currency": "Tanzanian Shilling", "alphabeticCode": "TZS", "numericCode": "834", "minorUnit": "2", "fund": ""},
    {"entity": "THAILAND", "currency": "Baht", "alphabeticCode": "THB", "numericCode": "764", "minorUnit": "2", "fund": ""},
    {"entity": "TIMOR-LESTE", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "TOGO", "currency": "CFA Franc BCEAO", "alphabeticCode": "XOF", "numericCode": "952", "minorUnit": "0", "fund": ""},
    {"entity": "TOKELAU", "currency": "New Zealand Dollar", "alphabeticCode": "NZD", "numericCode": "554", "minorUnit": "2", "fund": ""},
    {"entity": "TONGA", "currency": "Pa’anga", "alphabeticCode": "TOP", "numericCode": "776", "minorUnit": "2", "fund": ""},
    {"entity": "TRINIDAD AND TOBAGO", "currency": "Trinidad and Tobago Dollar", "alphabeticCode": "TTD", "numericCode": "780", "minorUnit": "2", "fund": ""},
    {"entity": "TUNISIA", "currency": "Tunisian Dinar", "alphabeticCode": "TND", "numericCode": "788", "minorUnit": "3", "fund": ""},
    {"entity": "TURKEY", "currency": "Turkish Lira", "alphabeticCode": "TRY", "numericCode": "949", "minorUnit": "2", "fund": ""},
    {"entity": "TURKMENISTAN", "currency": "Turkmenistan New Manat", "alphabeticCode": "TMT", "numericCode": "934", "minorUnit": "2", "fund": ""},
    {"entity": "TURKS AND CAICOS ISLANDS (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "TUVALU", "currency": "Australian Dollar", "alphabeticCode": "AUD", "numericCode": "036", "minorUnit": "2", "fund": ""},
    {"entity": "UGANDA", "currency": "Uganda Shilling", "alphabeticCode": "UGX", "numericCode": "800", "minorUnit": "0", "fund": ""},
    {"entity": "UKRAINE", "currency": "Hryvnia", "alphabeticCode": "UAH", "numericCode": "980", "minorUnit": "2", "fund": ""},
    {"entity": "UNITED ARAB EMIRATES (THE)", "currency": "UAE Dirham", "alphabeticCode": "AED", "numericCode": "784", "minorUnit": "2", "fund": ""},
    {"entity": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)", "currency": "Pound Sterling", "alphabeticCode": "GBP", "numericCode": "826", "minorUnit": "2", "fund": ""},
    {"entity": "UNITED STATES MINOR OUTLYING ISLANDS (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "UNITED STATES OF AMERICA (THE)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "UNITED STATES OF AMERICA (THE)", "currency": "US Dollar (Next day)", "alphabeticCode": "USN", "numericCode": "997", "minorUnit": "2", "fund": "TRUE"},
    {"entity": "URUGUAY", "currency": "Peso Uruguayo", "alphabeticCode": "UYU", "numericCode": "858", "minorUnit": "2", "fund": ""},
    {"entity": "URUGUAY", "currency": "Uruguay Peso en Unidades Indexadas (URUIURUI)", "alphabeticCode": "UYI", "numericCode": "940", "minorUnit": "0", "fund": "TRUE"},
    {"entity": "UZBEKISTAN", "currency": "Uzbekistan Sum", "alphabeticCode": "UZS", "numericCode": "860", "minorUnit": "2", "fund": ""},
    {"entity": "VANUATU", "currency": "Vatu", "alphabeticCode": "VUV", "numericCode": "548", "minorUnit": "0", "fund": ""},
    {"entity": "VENEZUELA (BOLIVARIAN REPUBLIC OF)", "currency": "Bolívar", "alphabeticCode": "VEF", "numericCode": "937", "minorUnit": "2", "fund": ""},
    {"entity": "VIET NAM", "currency": "Dong", "alphabeticCode": "VND", "numericCode": "704", "minorUnit": "0", "fund": ""},
    {"entity": "VIRGIN ISLANDS (BRITISH)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "VIRGIN ISLANDS (U.S.)", "currency": "US Dollar", "alphabeticCode": "USD", "numericCode": "840", "minorUnit": "2", "fund": ""},
    {"entity": "WALLIS AND FUTUNA", "currency": "CFP Franc", "alphabeticCode": "XPF", "numericCode": "953", "minorUnit": "0", "fund": ""},
    {"entity": "WESTERN SAHARA", "currency": "Moroccan Dirham", "alphabeticCode": "MAD", "numericCode": "504", "minorUnit": "2", "fund": ""},
    {"entity": "YEMEN", "currency": "Yemeni Rial", "alphabeticCode": "YER", "numericCode": "886", "minorUnit": "2", "fund": ""},
    {"entity": "ZAMBIA", "currency": "Zambian Kwacha", "alphabeticCode": "ZMW", "numericCode": "967", "minorUnit": "2", "fund": ""},
    {"entity": "ZIMBABWE", "currency": "Zimbabwe Dollar", "alphabeticCode": "ZWL", "numericCode": "932", "minorUnit": "2", "fund": ""},
    {"entity": "ZZ01_Bond Markets Unit European_EURCO", "currency": "Bond Markets Unit European Composite Unit (EURCO)", "alphabeticCode": "XBA", "numericCode": "955", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ02_Bond Markets Unit European_EMU-6", "currency": "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "alphabeticCode": "XBB", "numericCode": "956", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ03_Bond Markets Unit European_EUA-9", "currency": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "alphabeticCode": "XBC", "numericCode": "957", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ04_Bond Markets Unit European_EUA-17", "currency": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "alphabeticCode": "XBD", "numericCode": "958", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ06_Testing_Code", "currency": "Codes specifically reserved for testing purposes", "alphabeticCode": "XTS", "numericCode": "963", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ07_No_Currency", "currency": "The codes assigned for transactions where no currency is involved", "alphabeticCode": "XXX", "numericCode": "999", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ08_Gold", "currency": "Gold", "alphabeticCode": "XAU", "numericCode": "959", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ09_Palladium", "currency": "Palladium", "alphabeticCode": "XPD", "numericCode": "964", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ10_Platinum", "currency": "Platinum", "alphabeticCode": "XPT", "numericCode": "962", "minorUnit": "N.A.", "fund": ""},
    {"entity": "ZZ11_Silver", "currency": "Silver", "alphabeticCode": "XAG", "numericCode": "961", "minorUnit": "N.A.", "fund": ""}
];