/*jslint browser: true, unparam: true, evil: true*/
window.styleLibrary = {};
window.defaultStyleLibrary = {};
window.defaultStyleLibrary['sea wolf'] = {
    "name": "sea wolf",
    "scrollBarBackgroundColor": "#1e1e20",
    "scrollBarBoxColor": "#2a2c2b",
    "scrollBarActiveColor": "#374140",
    "scrollBarBoxWidth": 8,
    "scrollBarBoxMargin": 2,
    "scrollBarBoxBorderRadius": 3,
    "scrollBarBorderColor": "#1e1e20",
    "scrollBarBorderWidth": 0.5,
    "scrollBarWidth": 11,
    "scrollBarBoxMinSize": 15,
    "scrollBarCornerBorderColor": "#364036",
    "scrollBarCornerBackgroundColor": "#2a2c29",
    "treeArrowClickRadius": 5,
    "treeGridHeight": 250,
    "treeArrowHeight": 8,
    "treeArrowWidth": 13,
    "treeArrowColor": "#dc3522",
    "treeArrowBorderColor": "#2a2c2b",
    "treeArrowBorderWidth": 1,
    "treeArrowMarginRight": 5,
    "treeArrowMarginLeft": 0,
    "treeArrowMarginTop": 6,
    "filterTextPrefix": "(filtered) ",
    "editCellFontSize": "16px",
    "editCellFontFamily": "sans-serif",
    "editCellPaddingLeft": 4,
    "editCellBoxShadow": "0 2px 5px rgba(0,0,0,0.4)",
    "editCellBorder": "solid 1px rgba(110, 168, 255, 1)",
    "contextMenuItemMargin": "2px",
    "contextMenuItemBorderRadius": "3px",
    "contextMenuLabelMargin": "0 3px 0 0",
    "contextMenuLabelDisplay": "inline-block",
    "contextMenuLabelMinWidth": "75px",
    "contextMenuLabelMaxWidth": "700px",
    "contextMenuHoverBackground": "rgba(182, 205, 250, 1)",
    "contextMenuColor": "rgba(43, 48, 43, 1)",
    "contextMenuHoverColor": "rgba(43, 48, 153, 1)",
    "contextMenuFontSize": "16px",
    "contextMenuFontFamily": "sans-serif",
    "contextMenuBackground": "rgba(240, 240, 240, 1)",
    "contextMenuBorder": "solid 1px rgba(158, 163, 169, 1)",
    "contextMenuPadding": "2px",
    "contextMenuBorderRadius": "3px",
    "contextMenuOpacity": "0.98",
    "contextMenuFilterInvalidExpresion": "rgba(237, 155, 156, 1)",
    "contextMenuMarginTop": -3,
    "contextMenuMarginLeft": 3,
    "autosizePadding": 5,
    "autosizeHeaderCellPadding": 8,
    "minHeight": 24,
    "minRowHeight": 24,
    "minColumnWidth": 45,
    "columnWidth": 250,
    "backgroundColor": "#1e1e20",
    "headerOrderByArrowHeight": 8,
    "headerOrderByArrowWidth": 13,
    "headerOrderByArrowColor": "#dc3522",
    "headerOrderByArrowBorderColor": "#2a2c2b",
    "headerOrderByArrowBorderWidth": 1,
    "headerOrderByArrowMarginRight": 5,
    "headerOrderByArrowMarginLeft": 0,
    "headerOrderByArrowMarginTop": 6,
    "cellHeightWithChildGrid": 150,
    "cellWidthWithChildGrid": 250,
    "cellHeight": 24,
    "cellFont": "16px sans-serif",
    "cellPaddingTop": 5,
    "cellAutoResizePadding": 13,
    "cellPaddingLeft": 5,
    "cellPaddingRight": 7,
    "cellAlignment": "left",
    "cellColor": "#d9cb9e",
    "cellBackgroundColor": "#1e1e20",
    "cellHoverColor": "#2a2c2b",
    "cellHoverBackgroundColor": "#2a2c2b",
    "cellSelectedColor": "#d9cb9e",
    "cellSelectedBackgroundColor": "#374140",
    "cellBorderWidth": 0.25,
    "cellBorderColor": "#2a2c2b",
    "activeCellFont": "16px sans-serif",
    "activeCellPaddingTop": 5,
    "activeCellPaddingLeft": 5,
    "activeCellPaddingRight": 7,
    "activeCellAlignment": "left",
    "activeCellColor": "#d9cb9e",
    "activeCellBackgroundColor": "#1e1e20",
    "activeCellHoverColor": "#374140",
    "activeCellHoverBackgroundColor": "#374140",
    "activeCellSelectedColor": "#d9cb9e",
    "activeCellSelectedBackgroundColor": "#374140",
    "activeCellBorderWidth": 0.25,
    "activeCellBorderColor": "#1e1e20",
    "headerCellPaddingTop": 5,
    "headerCellPaddingLeft": 5,
    "headerCellPaddingRight": 7,
    "headerCellHeight": 25,
    "headerCellBorderWidth": 0.25,
    "headerCellBorderColor": "#1e1e20",
    "headerCellFont": "16px sans-serif",
    "headerCellColor": "#d9cb9e",
    "headerCellBackgroundColor": "#2a2c2b",
    "headerCellHoverColor": "#d9cb9e",
    "headerCellHoverBackgroundColor": "#2a2c2b",
    "activeHeaderCellColor": "#d9cb9e",
    "activeHeaderBackgroundColor": "#2a2c2b",
    "cornerCellBorderColor": "#1e1e20",
    "cornerCellBackgroundColor": "#2a2c2b",
    "headerRowWidth": 57,
    "rowHeaderCellPaddingTop": 5,
    "rowHeaderCellPaddingLeft": 5,
    "rowHeaderCellPaddingRight": 5,
    "rowHeaderCellHeight": 25,
    "rowHeaderCellBorderWidth": 0.25,
    "rowHeaderCellBorderColor": "#1e1e20",
    "rowHeaderCellFont": "16px sans-serif",
    "rowHeaderCellColor": "#d9cb9e",
    "rowHeaderCellBackgroundColor": "#2a2c2b",
    "rowHeaderCellHoverColor": "#d9cb9e",
    "rowHeaderCellHoverBackgroundColor": "#2a2c2b",
    "rowHeaderCellSelectedColor": "#d9cb9e",
    "rowHeaderCellSelectedBackgroundColor": "#2a2c2b",
    "activeRowHeaderCellColor": "#d9cb9e",
    "activeRowHeaderCellBackgroundColor": "#2a2c2b",
    "activeCellOverlayBorderColor": "#dc3522",
    "activeCellOverlayBorderWidth": 1.25,
    "selectionOverlayBorderColor": "#dc3522",
    "selectionOverlayBorderWidth": 1.25,
    "reorderMarkerIndexBorderColor": "#dc3522",
    "reorderMarkerIndexBorderWidth": 2.75,
    "reorderMarkerBackgroundColor": "#dc3522",
    "reorderMarkerBorderColor": "#dc3522",
    "reorderMarkerBorderWidth": 1.25,
    "gridBorderColor": "#2a2c2b",
    "gridBorderWidth": 1
};
window.defaultStyleLibrary.dark = {
    "name": "dark",
    "scrollBarBackgroundColor": "#2a2b28",
    "scrollBarBoxColor": "#393939",
    "scrollBarActiveColor": "rgba(125, 125, 125, 1)",
    "scrollBarBoxWidth": 8,
    "scrollBarBoxMargin": 2,
    "scrollBarBoxBorderRadius": 3,
    "scrollBarBorderColor": "#191a18",
    "scrollBarBorderWidth": 0.5,
    "scrollBarWidth": 11,
    "scrollBarBoxMinSize": 15,
    "scrollBarCornerBorderColor": "#364036",
    "scrollBarCornerBackgroundColor": "#2a2c29",
    "treeArrowClickRadius": 5,
    "treeGridHeight": 250,
    "treeArrowHeight": 8,
    "treeArrowWidth": 13,
    "treeArrowColor": "rgba(155, 155, 155, 1)",
    "treeArrowBorderColor": "rgba(195, 199, 202, 1)",
    "treeArrowBorderWidth": 1,
    "treeArrowMarginRight": 5,
    "treeArrowMarginLeft": 0,
    "treeArrowMarginTop": 6,
    "filterTextPrefix": "(filtered) ",
    "editCellFontSize": "16px",
    "editCellFontFamily": "sans-serif",
    "editCellPaddingLeft": 4,
    "editCellBoxShadow": "0 2px 5px rgba(0,0,0,0.4)",
    "editCellBorder": "solid 1px rgba(110, 168, 255, 1)",
    "contextMenuItemMargin": "2px",
    "contextMenuItemBorderRadius": "3px",
    "contextMenuLabelMargin": "0 3px 0 0",
    "contextMenuLabelDisplay": "inline-block",
    "contextMenuLabelMinWidth": "75px",
    "contextMenuLabelMaxWidth": "700px",
    "contextMenuHoverBackground": "rgba(182, 205, 250, 1)",
    "contextMenuColor": "rgba(43, 48, 43, 1)",
    "contextMenuHoverColor": "rgba(43, 48, 153, 1)",
    "contextMenuFontSize": "16px",
    "contextMenuFontFamily": "sans-serif",
    "contextMenuBackground": "rgba(240, 240, 240, 1)",
    "contextMenuBorder": "solid 1px rgba(158, 163, 169, 1)",
    "contextMenuPadding": "2px",
    "contextMenuBorderRadius": "3px",
    "contextMenuOpacity": "0.98",
    "contextMenuFilterInvalidExpresion": "rgba(237, 155, 156, 1)",
    "contextMenuMarginTop": -3,
    "contextMenuMarginLeft": 3,
    "autosizePadding": 5,
    "autosizeHeaderCellPadding": 8,
    "minHeight": 24,
    "minRowHeight": 24,
    "minColumnWidth": 45,
    "columnWidth": 250,
    "backgroundColor": "#1d201d",
    "headerOrderByArrowHeight": 8,
    "headerOrderByArrowWidth": 13,
    "headerOrderByArrowColor": "rgba(155, 155, 155, 1)",
    "headerOrderByArrowBorderColor": "rgba(195, 199, 202, 1)",
    "headerOrderByArrowBorderWidth": 1,
    "headerOrderByArrowMarginRight": 5,
    "headerOrderByArrowMarginLeft": 0,
    "headerOrderByArrowMarginTop": 6,
    "cellHeightWithChildGrid": 150,
    "cellWidthWithChildGrid": 250,
    "cellHeight": 24,
    "cellFont": "16px sans-serif",
    "cellPaddingTop": 5,
    "cellAutoResizePadding": 13,
    "cellPaddingLeft": 5,
    "cellPaddingRight": 7,
    "cellAlignment": "left",
    "cellColor": "#b8b8b8",
    "cellBackgroundColor": "#2a2c29",
    "cellHoverColor": "#b8b8b8",
    "cellHoverBackgroundColor": "#2a2c29",
    "cellSelectedColor": "#a9c3a9",
    "cellSelectedBackgroundColor": "#444649",
    "cellBorderWidth": 0.25,
    "cellBorderColor": "#060606",
    "activeCellFont": "16px sans-serif",
    "activeCellPaddingTop": 5,
    "activeCellPaddingLeft": 5,
    "activeCellPaddingRight": 7,
    "activeCellAlignment": "left",
    "activeCellColor": "#cfd9ca",
    "activeCellBackgroundColor": "#4d514c",
    "activeCellHoverColor": "#ccd6c7",
    "activeCellHoverBackgroundColor": "#2a2c29",
    "activeCellSelectedColor": "#c8c8c8",
    "activeCellSelectedBackgroundColor": "#4d514c",
    "activeCellBorderWidth": 0.25,
    "activeCellBorderColor": "#515151",
    "headerCellPaddingTop": 5,
    "headerCellPaddingLeft": 5,
    "headerCellPaddingRight": 7,
    "headerCellHeight": 25,
    "headerCellBorderWidth": 0.25,
    "headerCellBorderColor": "#2a2c29",
    "headerCellFont": "16px sans-serif",
    "headerCellColor": "#a7a7a7",
    "headerCellBackgroundColor": "#454843",
    "headerCellHoverColor": "#b0b0b0",
    "headerCellHoverBackgroundColor": "#5b6359",
    "activeHeaderCellColor": "#bfc2be",
    "activeHeaderCellBackgroundColor": "#61655e",
    "cornerCellBorderColor": "rgba(202, 202, 202, 1)",
    "cornerCellBackgroundColor": "#61655e",
    "headerRowWidth": 57,
    "rowHeaderCellPaddingTop": 5,
    "rowHeaderCellPaddingLeft": 5,
    "rowHeaderCellPaddingRight": 5,
    "rowHeaderCellHeight": 25,
    "rowHeaderCellBorderWidth": 0.25,
    "rowHeaderCellBorderColor": "#1c1c1c",
    "rowHeaderCellFont": "16px sans-serif",
    "rowHeaderCellColor": "#a7a7a7",
    "rowHeaderCellBackgroundColor": "#454843",
    "rowHeaderCellHoverColor": "#aeaeae",
    "rowHeaderCellHoverBackgroundColor": "#5a6258",
    "rowHeaderCellSelectedColor": "rgba(50, 50, 50, 1)",
    "rowHeaderCellSelectedBackgroundColor": "rgba(217, 217, 217, 1)",
    "activeRowHeaderCellColor": "rgba(0, 0, 0, 1)",
    "activeRowHeaderCellBackgroundColor": "#61655e",
    "activeCellOverlayBorderColor": "#5d6059",
    "activeCellOverlayBorderWidth": 2,
    "selectionOverlayBorderColor": "#3e413d",
    "selectionOverlayBorderWidth": 1.25,
    "reorderMarkerIndexBorderColor": "rgba(66, 133, 244, 1)",
    "reorderMarkerIndexBorderWidth": 2.75,
    "reorderMarkerBackgroundColor": "rgba(0, 0, 0, 0.1)",
    "reorderMarkerBorderColor": "rgba(0, 0, 0, 0.2)",
    "reorderMarkerBorderWidth": 1.25,
    "gridBorderColor": "#505050",
    "gridBorderWidth": 1
};
