name: Publish documentation

on: workflow_dispatch

jobs:
  publish-documentation:
      name: Publish documentation
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Node
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - name: Install dependencies
          run: npm ci
        - name: Build debug version
          run: npm run build-dev
        - name: Build documentation
          run: npm run build-docs
        # This will make documentation available at
        # https://<username>.github.io/canvas-datagrid/docs/
        - name: Publish documentation to GitHub pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: .
